select ROW_ID, CAMPO31 NUMCLIENTE, CAMPO30 CUPS, CAMPO32 CUPSMC, CAMPO38 OS, ACAO from 
(select A.* ,
     RANK() OVER (PARTITION BY A.CAMPO30 ORDER BY A.LAST_UPD DESC) ordem
from SIEBEL.CX_INTERF_ZEUS A     
 where 
  A.INTERFACE = 'SBLEPS01'
   and STATUS = 'ENVIADOEPS'
   and A.ACAO = 'baixa'
   and A.CAMPO30 = 'BR0016020000621038MW') where ordem = 1