SELECT
	CAT.NAME	AS "CATEGORIA",
	MSG.NAME	AS "NOME",
	CASE
		WHEN ALIAS.TEXT IS NOT NULL THEN ALIAS.TEXT
		WHEN EXT.STRING_VALUE IS NOT NULL THEN EXT.STRING_VALUE
		ELSE DFLT.STRING_VALUE
	END AS "TEXTO"	
FROM SIEBEL.S_ERR_MSG_CAT CAT
RIGHT JOIN SIEBEL.S_ERR_MSG MSG ON MSG.ERR_MSG_CAT_ID = CAT.ROW_ID
LEFT JOIN SIEBEL.S_ERR_MSG_INTL ALIAS ON ALIAS.ERR_MSG_ID = MSG.ROW_ID
LEFT JOIN SIEBEL.S_SYM_STR_INTL EXT ON EXT.SYM_STR_KEY = MSG.TEXT_REF AND EXT.REPOSITORY_ID = MSG.REPOSITORY_ID
LEFT JOIN SIEBEL.S_SYM_STR_INTL DFLT ON DFLT.SYM_STR_KEY = MSG.TEXT_REF AND DFLT.REPOSITORY_ID = MSG.REPOSITORY_ID
WHERE 1=1
AND CAT.NAME = 'GOL Miles Voucher';
AND (
	ALIAS.TEXT LIKE ''
	OR EXT.STRING_VALUE LIKE ''
	OR DFLT.STRING_VALUE LIKE ''
);
