SELECT
    NORMA.NAME AS "NOME",
    NORMA.OBJECT_NAME AS "WORKFLOW",
    GRUPO.NAME AS "GRUPO_NORMAS",
    LCOL.NAME AS "COND_FIELD",
    COND.COND_OPERAND AS "COND_OPERACAO",
    COND.VAL AS "COND_META",
    ADEF.NAME AS "ACAO",
    ACAO.SEQUENCE AS "ACAO_SEQ",
    ARG.NAME AS "ARGUMENTO",
    ARG.DEFAULT_VALUE AS "META"
FROM SIEBEL.S_ESCL_GROUP GRUPO
LEFT JOIN SIEBEL.S_ESCL_RULE NORMA ON NORMA.GROUP_ID = GRUPO.ROW_ID
LEFT JOIN SIEBEL.S_ESCL_COND COND ON COND.RULE_ID = NORMA.ROW_ID
LEFT JOIN SIEBEL.S_ESCL_COL COL ON COL.NAME = COND.LINK_COL_NAME
LEFT JOIN SIEBEL.S_ESCL_LINK_COL LCOL ON LCOL.COND_COL_ID = COL.ROW_ID
LEFT JOIN SIEBEL.S_ESCL_ACTION ACAO ON ACAO.RULE_ID = NORMA.ROW_ID
LEFT JOIN SIEBEL.S_ACTION_DEFN ADEF ON ADEF.ROW_ID = ACAO.ACTION_ID
LEFT JOIN SIEBEL.S_ACTION_ARG ARG ON ARG.ACTION_ID = ADEF.ROW_ID
WHERE ARG.DEFAULT_VALUE = 'CEG Transportar Processo Interface EAI';