SELECT
	SVR.SBLSRVR_NAME			AS "SERVER_NAME",
	SVR.HOST_NAME				AS "HOST_NAME",
	COMP.CC_NAME				AS "COMPONENT",
	COMP.CP_DISP_RUN_STATE		AS "STATE",
	COMP.CP_STATUS				AS "STATUS",
	PAR.PA_NAME					AS "PARAMETER",
	PAR.PA_VALUE				AS "VALUE",
	PAR.PA_INITVAL				AS "VALUE_ON_RESTART"
FROM SIEBEL.V_SA_SBLSRVR SVR
RIGHT JOIN SIEBEL.V_SRS_COMP COMP ON COMP.SV_NAME = SVR.SBLSRVR_NAME
LEFT JOIN SIEBEL.V_SRS_PARM PAR ON PAR.CC_ALIAS = COMP.ROW_ID
WHERE COMP.CC_NAME LIKE 'EAI Object Manager Arg%ENU%'
AND PAR.PA_NAME LIKE 'Workspace Branch Name';