SELECT DISTINCT
    JOBS.ROW_ID             AS "ID",
    ACT.DISPLAY_NAME        AS "COMPONENT",
    TEMP.NAME               AS "TEMPLATE_SHORT_NAME",
    TEMP.DISPLAY_NAME       AS "TEMPLATE_NAME",
    JOBS.EXEC_SRVR_NAME     AS "SERVER",
    JOBS.ENTERPRISE_NAME    AS "ENTERPRISE",
    JOBS.REQ_MODE           AS "MODE",
    JOBS.STATUS             AS "STATUS",
    --JOBS.DESC_TEXT          AS "DESCRIPTION",
    JOBS.COMPLETION_TEXT    AS "COMPLETITION_INFO",
    ACPAR.NAME,
    ACPAR.PARAM_VALUE
FROM SIEBEL.S_SRM_REQUEST JOBS
LEFT JOIN SIEBEL.S_SRM_ACTION ACT ON ACT.ROW_ID = JOBS.ACTION_ID
LEFT JOIN SIEBEL.S_SRM_ACTION TEMP ON TEMP.PAR_ACTION_ID = ACT.ROW_ID
LEFT JOIN SIEBEL.S_SRM_ACT_PARAM ACPAR ON ACPAR.ACTION_ID = TEMP.ROW_ID
LEFT JOIN SIEBEL.S_SRM_REQ_PARAM PAR ON PAR.ACTPARAM_ID = ACPAR.ROW_ID
WHERE 1=1
AND ACT.DISPLAY_NAME = 'Retrocredito Job Template 1'
--AND TEMP.NAME = 'ContaFamiliaJobTemplate'
AND JOBS.STATUS = 'ACTIVE'
ORDER BY JOBS.ROW_ID ASC;
--AND JOBS.DESC_TEXT LIKE '%Recurrence%'
AND JOBS.CREATED >= SYSDATE - 30;
AND JOBS.ROW_ID IN ('1-1NU2WLAX', '1-1NU2WLKM');

UPDATE SIEBEL.S_SRM_REQUEST JOBS
SET JOBS.STATUS = 'CREATING', -- LOV: SRM_STATUS
    JOBS.COMPLETION_TEXT = NULL
WHERE JOBS.ROW_ID = '1-1NU3DCD2';

