SELECT
    NVL(PL.NAME, ' ') AS ""LISTA_DE_PRECO"",
	NVL(BU.NAME, ' ') AS ""LST_PRECO_ORGANIZACAO"",
	PL.X_NUM_PARCELA AS ""LST_PRECO_QTD_PARCELAS"",
	PL.EFF_START_DT AS ""LST_PRECO_VIGENCIA_DE"",
	PL.EFF_END_DT AS ""LST_PRECO_VIGENCIA_ATE"",
	NVL(PL.DESC_TEXT, ' ') AS ""LST_PRECO_DESCRICAO"",
	NVL(ITEM.PERIOD_CD, ' ') AS ""ITEM_TIPO"",
	NVL(ITEM.PROD_NAME, ' ') AS ""ITEM_EQUIP/OS/ITEM_ORCAMENTO"",
	ITEM.EFF_START_DT AS ""ITEM_DATA_INICIO"",
	ITEM.EFF_END_DT AS ""ITEM_DATA_TERMINO"",
	NVL(PRD.DATA_SRC, ' ') AS ""ITEM_EQUIP_MARCA"",
	NVL(PRD.DETAIL_TYPE_CD, ' ') AS ""ITEM_EQUIP_TIPO"",
	NVL(PRD.SALES_SRVC_FLG, ' ') AS ""ITEM_PRODUTO_SERVICO"",
	ITEM.STD_PRI_UNIT AS ""ITEM_PRECO_TABELA"",
	NVL(ITEM.PRI_METH_CD, ' ') AS ""ITEM_METODO_PRECO"",
	ITEM.SVC_PER_PROD_PCT AS ""ITEM_PORC_PRECO_SERVICO"",
    NVL(ITEM.DESC_TEXT, ' ') AS ""ITEM_DECRICAO"",
    PRD.PART_NUM AS ""ITEM_NUM_PECA"",
    NVL(PRD.PRICE_TYPE_CD, ' ') AS ""ITEM_TIPO_PRECO"",
    NVL(PRD.UOM_CD, ' ') AS ""ITEM_UNIDADE_MEDIDA"",
    ITEM.DFLT_COST_UNIT AS ""ITEM_CUSTO""
FROM SIEBEL.S_PRI_LST PL                                                -- LISTA DE PRECO
LEFT JOIN SIEBEL.S_PRI_LST_ITEM ITEM ON ITEM.PRI_LST_ID = PL.ROW_ID     -- ITEM DA LISTA DE PRECO / PREÇO DE SERVICO
LEFT JOIN SIEBEL.S_PROD_INT PRD ON PRD.ROW_ID = ITEM.PROD_ID            -- PRODUTO DO ITEM DA LISTA
LEFT JOIN SIEBEL.S_PRI_LST_BU PLBU ON PLBU.PRI_LST_ID = PL.ROW_ID      -- INTER TABLE DA ORGANIZATION
LEFT JOIN SIEBEL.S_BU BU ON BU.ROW_ID = PLBU.BU_ID                     -- ORGANIZATION
WHERE (
    PL.EFF_END_DT IS NULL
    OR PL.EFF_END_DT >= SYSDATE
)
AND (
    ITEM.EFF_END_DT IS NULL
    OR ITEM.EFF_END_DT >= SYSDATE
)
ORDER BY PL.NAME, BU.NAME, ITEM.PERIOD_CD, ITEM.PROD_NAME ASC