SELECT
    PF.ROW_ID,
    PF.LAST_UPD,
    USR.LOGIN,
    PF.SYS_PREF_CD AS "PREFERENCIA",
    PF.VAL AS "VALOR",
    PF.COMMENTS AS "COMENTARIOS"
FROM SIEBEL.S_SYS_PREF PF
LEFT JOIN SIEBEL.S_USER USR ON USR.ROW_ID = PF.LAST_UPD_BY
WHERE 1=1
AND PF.SYS_PREF_CD IN (
    'GOL MILESPURCHASE CAMPAIGN',
    'GOL MILESBENEFIT CAMPAIGN',
    'GOL AIRLINE CAMPAIGN'
);
--AND PF.SYS_PREF_CD IN ('GOL_RESPONSYS_ACCRUAL', 'GOL_RESPONSYS_REDEMPTION', 'GOL_RESPONSYS_CF_TXN_MTR', 'GOL_RESPONSYS_RED_NAEREO', 'GOL_RESPONSYS_ACCRUAL0', 'GOL_RESPONSYS_CF_TXN_MBR')

UPDATE SIEBEL.S_SYS_PREF PF
SET PF.VAL = 'Sleeping'
WHERE PF.ROW_ID = '1-1LC2SA9N';