SELECT DISTINCT
	VOD.VOD_NAME AS "NOME",
	ATD.DATA_TYPE_CD AS "TIPO_DADOS"
FROM SIEBEL.S_VOD VOD
LEFT JOIN SIEBEL.S_VOD_VER VER ON VER.VOD_ID = VOD.ROW_ID
LEFT JOIN SIEBEL.S_ISS_ATTR_DEF ATD ON ATD.VOD_ID = VOD.ROW_ID
WHERE VOD.VOD_NAME IN (
    'Aquecedor'
);