SELECT
    PROJ.JWS_NAME AS "NOME",
    VOD.VOD_NAME AS "NOME_PRODUTO",
    VOD.DESC_TEXT AS "DESCRIÇÃO"
FROM SIEBEL.S_ISS_JWS_ITEM INTER
INNER JOIN SIEBEL.S_ISS_JWS PROJ ON PROJ.ROW_ID = INTER.JWS_ID
INNER JOIN SIEBEL.S_VOD VOD ON VOD.ROW_ID = INTER.VOD_ID
WHERE PROJ.JWS_NAME = 'OFERTA_20190119';