SELECT
    BC.ROW_ID,
    BC.NAME NOME_BC,
    BC.TABLE_NAME NOME_TABELA_BC
FROM SIEBEL.S_BUSCOMP BC;

SELECT * FROM SIEBEL.S_BUSCOMP WHERE NAME = 'AMS State Transition';

------------------- BUSCAR A TELA ONDE UM FIELD ESTA -------------------
SELECT DISTINCT
    COALESCE(APP.NAME, ' ')                                        	AS "APLICACAO",
    COALESCE(SLV1.VAL, SCR.VIEWBAR_TEXT, SYV2.STRING_VALUE, ' ')	AS "TELA",
    COALESCE(SCR.NAME, ' ')                                     	AS "SCREEN_NAME",
    COALESCE(SCRVW.PAR_CATEGORY, ' ')                           	AS "PARENT_CATEGORY",
    COALESCE(SCRVW.VIEWBAR_TEXT, SYV.STRING_VALUE, ' ')         	AS "VIEWBAR_TEXT",
    COALESCE(VW.NAME, ' ')                                      	AS "VIEW_NAME",
    COALESCE(BO.NAME, ' ')                                      	AS "BUSOBJ_NAME",
    COALESCE(APLT.NAME, ' ')                                    	AS "APPLET_NAME",
    COALESCE(BC.NAME, ' ')                                      	AS "BUSCOMP_NAME"
    --COALESCE(SFD.NAME, ' ')										  AS "FIELD_NAME"
FROM SIEBEL.S_WORKSPACE WPP
RIGHT JOIN SIEBEL.S_APPLICATION APP ON APP.WS_ID = WPP.ROW_ID
RIGHT JOIN SIEBEL.S_SCR_MENU_ITEM SCMI ON SCMI.APPLICATION_ID = APP.ROW_ID --AND SCMI.WS_ID = WPP.ROW_ID
RIGHT JOIN SIEBEL.S_SCREEN SCR ON SCR.NAME = SCMI.SCREEN_NAME --AND SCR.WS_ID = WPP.ROW_ID
RIGHT JOIN SIEBEL.S_SCREEN_VIEW SCRVW ON SCRVW.SCREEN_ID = SCR.ROW_ID --AND SCRVW.WS_ID = WPP.ROW_ID
RIGHT JOIN SIEBEL.S_VIEW VW ON VW.NAME = SCRVW.NAME OR VW.NAME = SCRVW.VIEW_NAME --AND VW.WS_ID = WPP.ROW_ID
RIGHT JOIN SIEBEL.S_VIEW_WEB_TMPL VWT ON VWT.VIEW_ID = VW.ROW_ID --AND VWT.WS_ID = WPP.ROW_ID
RIGHT JOIN SIEBEL.S_VIEW_WTMPL_IT VWTI ON VWTI.VIEW_WEB_TMPL_ID = VWT.ROW_ID --AND VWTI.WS_ID = WPP.ROW_ID
RIGHT JOIN SIEBEL.S_BUSOBJ BO ON BO.NAME = VW.BUSOBJ_NAME --AND BO.WS_ID = WPP.ROW_ID
RIGHT JOIN SIEBEL.S_APPLET APLT ON APLT.NAME = VWTI.APPLET_NAME --AND APLT.WS_ID = WPP.ROW_ID
RIGHT JOIN SIEBEL.S_BUSCOMP BC ON BC.NAME = APLT.BUSCOMP_NAME --AND BC.WS_ID = WPP.ROW_ID
--RIGHT JOIN SIEBEL.S_FIELD SFD ON SFD.BUSCOMP_ID = BC.ROW_ID
LEFT JOIN SIEBEL.S_LST_OF_VAL SLV1 ON SCR.VIEWBAR_TEXT = SLV1.NAME --AND SLV1.WS_ID = WPP.ROW_ID -- TRADUCAO DA VIEW
--INNER JOIN SIEBEL.S_WORKSPACE WPP ON APLT.WS_ID = WPP.ROW_ID AND APP.WS_ID = WPP.ROW_ID--AND SFD.WS_ID = WPP.ROW_ID
LEFT JOIN SIEBEL.S_SYM_STR SYM ON SYM.NAME = SCRVW.VIEWBAR_TEXT_REF OR SYM.NAME = SCRVW.STATUS_TEXT_REF OR SYM.NAME = SCRVW.MENU_TEXT_REF --AND SYM.WS_ID = WPP.ROW_ID
LEFT JOIN SIEBEL.S_SYM_STR_INTL SYV ON SYV.SYM_STR_ID = SYM.ROW_ID --AND SYV.WS_ID = WPP.ROW_ID
LEFT JOIN SIEBEL.S_SYM_STR SYM2 ON SYM2.NAME = SCR.VIEWBAR_TEXT_REF --AND SYM2.WS_ID = WPP.ROW_ID
LEFT JOIN SIEBEL.S_SYM_STR_INTL SYV2 ON SYV2.SYM_STR_ID = SYM2.ROW_ID --AND SYV2.WS_ID = WPP.ROW_ID
WHERE 1=1
AND WPP.NAME = 'MAIN'
--AND ROWNUM < 5;
AND (SYV.LANG_CD = 'ENU' AND SYV2.LANG_CD = 'ENU')
AND APLT.NAME = 'Workflow Object List Applet'
--AND BC.TABLE_NAME = 'S_LOY_ATTRDEFN'
--AND BC.NAME = 'GOL Voucher Request' --BUSINESS COMPONENT
--AND APP.INACTIVE_FLG = 'N'
AND APP.NAME IN (
    'Siebel Loyalty',
    --'Siebel Power Communications',
    'Siebel Web Tools'--,
    --'Siebel Sales Enterprise',
    --'Siebel Universal Agent',
    --'Siebel eSales'
);
--AND BC.NAME = 'LOY Attribute Definition' --BUSINESS COMPONENT
--AND BO.NAME = 'Account' --BUSINESS OBJECT
--AND VW.NAME = 'SIS OM Customer Account Portal View'; -- VIEW
/*
WHERE SFD.NAME = 'Account Status' --FIELD
AND BC.NAME IS NOT NULL
AND APLT.NAME IS NOT NULL
AND BO.NAME IS NOT NULL
AND VW.NAME IS NOT NULL
AND SCR.NAME IS NOT NULL;
*/


select * from SIEBEL.S_SCREEN SCR;

SELECT *
FROM SIEBEL.S_SYM_STR_INTL;