/* Criando user na base local

Criar nas tabelas de usuarios do siebel do .dbf: S_USER, S_CONTANCT e etc.

Lembrando que para isso, é preciso logar no SQLDBX (ou qualquer outro client de acesso a dbf.) com user "SIEBEL". 
A senha do user siebel é a mesma do user local.
*/
 

IF NOT EXISTS (SELECT NAME FROM SYSUSERS WHERE NAME= 'VMITRAUD') execute sp_adduser VMITRAUD
GRANT CONNECT To "VMITRAUD" IDENTIFIED BY "VMITRAUD"
sp_changegroup SSE_ROLE, VMITRAUD
GRANT CONNECT TO VMITRAUD IDENTIFIED BY VMITRAUD
GRANT GROUP TO SSE_ROLE
GRANT MEMBERSHIP IN GROUP SSE_ROLE TO VMITRAUD

--Marretar usuário nas tabelas SIEBEL


UPDATE SIEBEL.S_CONTACT SET PAR_ROW_ID = '1-1W6RN1' WHERE PAR_ROW_ID = '1-1OUZBH';

UPDATE SIEBEL.S_CONTACT SET ROW_ID = '1-1W6RN1' WHERE ROW_ID = '1-1OUZBH' ;

UPDATE SIEBEL.S_EMP_PER SET PAR_ROW_ID = '1-1W6RN1' WHERE PAR_ROW_ID = '1-1OUZBH';

UPDATE SIEBEL.S_EMP_PER SET ROW_ID = '1-1W6RN1' WHERE ROW_ID = '1-1OUZBH' ;

UPDATE SIEBEL.S_PARTY SET ROW_ID = '1-1W6RN1' WHERE ROW_ID = '1-1OUZBH' ;

UPDATE SIEBEL.S_PARTY_PER SET PERSON_ID = '1-1W6RN1' WHERE PERSON_ID = '1-1OUZBH';

UPDATE SIEBEL.S_USER SET PAR_ROW_ID = '1-1W6RN1', LOGIN = 'VMITRAUD' WHERE PAR_ROW_ID = '1-1OUZBH';

UPDATE SIEBEL.S_USER SET ROW_ID = '1-1W6RN1' WHERE ROW_ID = '1-1OUZBH' ;

UPDATE SIEBEL.S_CONTACT_BU SET CONTACT_ID = '1-1W6RN1' WHERE CONTACT_ID = '1-1OUZBH';

UPDATE SIEBEL.S_PER_RESP SET PER_ID = '1-1W6RN1' WHERE PER_ID = '1-1OUZBH';

UPDATE SIEBEL.S_POSTN_CON SET CON_ID = '1-1W6RN1' WHERE CON_ID = '1-1OUZBH';

COMMIT;


