--------------------- SELECIONAR USUÁRIO QUE ESTÁ BLOQUEANDO ---------------------
SELECT * FROM SIEBEL.S_VOD WHERE LOCKED_BY = 'E80571519';

------------------ ALTERAR DADOS DO USUÁRIO QUE ESTÁ BLOQUEANDO ------------------
UPDATE SIEBEL.S_VOD SV
SET SV.LOCKED_BY = 'E80571519'
WHERE SV.LOCKED_BY = '80571519';

update SIEBEL.S_PROJECT P
set P.LOCKED_FLG = 'N'
where P.ROW_ID = '8-1GNTDVY';