SELECT
    LOV.ROW_ID,
    LOV.TYPE                AS "TIPO",
	LOV.NAME                AS "COD_INDEPENDENTE_IDIOMA",
    LOV.VAL                 AS "EXIBIR_VALOR",
    SLA.NAME                AS "NOME_IDIOMA",
	--PLOV.VAL               AS "SUBTIPO",
	LOV.SUB_TYPE            AS "SUBTIPO",
	LOV.ORDER_BY            AS "ORDEM",
	LOV.LOW                 AS "BAIXO",
	LOV.HIGH                AS "ALTO",
	LOV.ACTIVE_FLG          AS "ATIVO",
	LOV.TRANSLATE_FLG       AS "TRADUZIR",
	LOV.MULTI_LINGUAL_FLG   AS "MULTILINGUE",
	LOV.RPLCTN_LVL_CD       AS "NIVEL_REPLICACAO",
	LOV.TARGET_LOW          AS "ALVO_BAIXO",
	LOV.TARGET_HIGH         AS "ALVO_ELEVADO",
	--LOV.WEIGHTING_FACTOR,
	--SLT.NAME,
	LOV.DESC_TEXT,
	--LOV.PAR_ROW_ID,
	--LOV.LANG_ID
    LOV.WS_INACTIVE_FLG,
    WSP.NAME                AS "WORKSPACE",
    REP.NAME                AS "REPOSITORY"
FROM SIEBEL.S_LST_OF_VAL LOV
LEFT JOIN SIEBEL.S_LST_OF_VAL PLOV ON PLOV.ROW_ID = LOV.PAR_ROW_ID
LEFT JOIN SIEBEL.S_LANG SLA ON SLA.LANG_CD = LOV.LANG_ID
LEFT JOIN SIEBEL.S_LIT SLT ON SLT.ROW_ID = LOV.BITMAP_ID
LEFT JOIN SIEBEL.S_WORKSPACE WS ON WS.ROW_ID = LOV.WS_ID
LEFT JOIN SIEBEL.S_WORKSPACE WSP ON WSP.ROW_ID = LOV.WS_ID
LEFT JOIN SIEBEL.S_REPOSITORY REP ON REP.ROW_ID = WSP.REPOSITORY_ID
WHERE 1=1
AND REP.NAME = 'Siebel Repository'
AND WS.NAME = 'MAIN'
AND LOV.WS_INACTIVE_FLG = 'N'
AND LOV.ACTIVE_FLG = 'Y'
--AND LOV.LANG_ID = 'ENU'
AND LOV.TYPE like 'GOL_CLUB_STATUS_SIG'
--AND LOV.VAL = 'Monthly'
ORDER BY LOV.VAL, LOV.SUB_TYPE, LOV.ORDER_BY ASC;
--AND LOV.ROW_ID = '1-PCMR-8Q0M';
--AND LOV.WS_ID = '1-PCMR-8Q0M'
--AND LOV.LANG_ID = 'PTB'
AND LOV.DESC_TEXT LIKE '[MROSA] 20/09/2021 - Squad B2C - Clube Smiles Corporativo [MVP]';
AND LOV.NAME = 'Hotel reservation agent';


UPDATE SIEBEL.S_LST_OF_VAL LOV
SET --LOV.NAME = 'Food and drinks',
    --LOV.VAL = 'Alimentos y bebidas'
    WS_INACTIVE_FLG = 'N'
WHERE LOV.TYPE = 'CORP_EMP_STATUS';
AND LOV.LANG_ID = 'ESN'
AND LOV.NAME = 'Alimentos y bebidas';

UPDATE SIEBEL.S_LST_OF_VAL LOV
SET WS_ID = '1-1NT4FEJG'
WHERE LOV.TYPE = 'CORPORATE_SEGMENT';

SELECT DISTINCT
    LOV.ROW_ID,
    LOV.PAR_ROW_ID,
    LOV.TYPE,
    LOV.SUB_TYPE,
    LOV.NAME,
    LOV.VAL,
    LOV.ACTIVE_FLG,
    LOV.LANG_ID,
    LOV.DESC_TEXT
FROM SIEBEL.S_LST_OF_VAL LOV
--WHERE LOV.ROW_ID = '0LPTB-4UOA1@';
WHERE LOV.ACTIVE_FLG = 'Y'
--AND LOV.PAR_ROW_ID IS NOT NULL;
AND LOV.TYPE = 'GOL_LOY_MILES_SRC_CHANNEL';
AND LOV.DESC_TEXT LIKE 'NV MCabral - 26/12/2018 - Teste ADM%';

SELECT COUNT(*)
FROM SIEBEL.S_LST_OF_VAL LOV
--WHERE LOV.ROW_ID = '0LPTB-4UOA1@';
WHERE LOV.TYPE = 'GVT_CODIGO_ENCERRAMENTO';



------------------------------------------------------
SELECT
	LOV.TYPE                AS "TIPO",
	LOV.VAL                 AS "EXIBIR_VALOR",
	LOV.NAME                AS "COD_INDEPENDENTE_IDIOMA",
    SLA.NAME                AS "NOME_IDIOMA",
	--PLOV.NAME               AS "",
	LOV.SUB_TYPE            AS "SUBTIPO",
	LOV.ORDER_BY            AS "ORDEM",
	LOV.LOW                 AS "BAIXO",
	LOV.HIGH                AS "ALTO",
	LOV.ACTIVE_FLG          AS "ATIVO",
	LOV.TRANSLATE_FLG       AS "TRADUZIR",
	LOV.MULTI_LINGUAL_FLG   AS "MULTILINGUE",
	LOV.RPLCTN_LVL_CD       AS "NIVEL_REPLICACAO",
	LOV.TARGET_LOW          AS "ALVO_BAIXO",
	LOV.TARGET_HIGH         AS "ALVO_ELEVADO"
	--LOV.WEIGHTING_FACTOR,
	--SLT.NAME,
	--LOV.DESC_TEXT,
	--LOV.PAR_ROW_ID,
	--LOV.LANG_ID
FROM SIEBEL.S_LST_OF_VAL LOV
LEFT JOIN SIEBEL.S_LST_OF_VAL PLOV ON PLOV.ROW_ID = LOV.PAR_ROW_ID
LEFT JOIN SIEBEL.S_LANG SLA ON SLA.LANG_CD = LOV.LANG_ID
LEFT JOIN SIEBEL.S_LIT SLT ON SLT.ROW_ID = LOV.BITMAP_ID
WHERE LOV.ACTIVE_FLG = 'Y'
AND LOV.TYPE = 'GVT_CHK_CLASS_POS_CANCEL_SALE'
AND LOV.NAME IN (
    SELECT
        LOV.NAME
    FROM SIEBEL.S_LST_OF_VAL LOV
    WHERE LOV.NAME LIKE '%AA'
    OR LOV.NAME LIKE '%Fixo Movel'
    OR LOV.NAME LIKE 'Analista Vendas'
    OR LOV.NAME LIKE 'Ots%'
    OR LOV.NAME LIKE 'Assistente Indicação'
)
ORDER BY LOV.NAME ASC;