SELECT
	--NVL(SVI.ROW_ID, ' ')										AS "ID",
	--NVL(SVI.RECORD_ID, ' ')										AS "ID_OBJETO",
    NVL(SVR.NAME, ' ')											AS "NOME_CONJ_REGRAS",
	NVL(SVR.BUSCOMP_NAME, ' ')									AS "NOME_BUSCOMP",	
    NVL(TO_CHAR(SVR.REV_NUM), ' ')								AS "NUMERO_VERSAO",
	NVL(TO_CHAR(SVI.RULE_SEQ_NUM), ' ')							AS "NUM_ULTIMA_ETAPA",
    NVL(SVI.RETURN_CD, ' ')										AS "CODIGO_DEVOLUCAO",
	NVL(SVI.ERR_MSG, ' ')										AS "MENSAGEM_DEVOLUCAO",
	NVL(TO_CHAR(SVI.INSTANCE_DT, 'DD/MM/YYYY HH24:MI:SS'), ' ') AS "DATA",
	NVL(SUS.LOGIN, ' ') 										AS "INICIADO_POR",
	NVL(SVI.STATUS_CD, ' ')										AS "STATUS",
    CASE
        WHEN SVI.STATUS_CD NOT IN ('Concluído', 'Completed') THEN VAL.RULE_EXPR
        ELSE ' '
    END                                                         AS "ESPRESSAO"
FROM SIEBEL.S_VALDN_INST SVI
INNER JOIN SIEBEL.S_VALDN_RL_SET SVR ON SVI.RULESET_ID = SVR.ROW_ID
INNER JOIN SIEBEL.S_VALDN_RULE VAL ON SVR.ROW_ID = VAL.RULE_SET_ID AND SVI.RULE_SEQ_NUM = VAL.SEQ_NUM
INNER JOIN SIEBEL.S_USER SUS ON SVI.CREATED_BY = SUS.ROW_ID

WHERE SVR.STATUS_CD = 'Active'
AND SVI.INSTANCE_DT >= SYSDATE - 1
--AND SUS.LOGIN = 'G0009411'
--AND SVI.STATUS_CD = 'Com erros'
--AND SVR.NAME = 'GOL Quiz Question Active Flag'
ORDER BY SVI.INSTANCE_DT DESC;