SELECT
    AP.ROW_ID,
    AP.NAME,
    AP.OBJ_LOCKED_FLG,
    AP.OBJ_LOCKED_BY,
    SUS.ROW_ID AS "ID_USUARIO",
    SUS.LOGIN AS "LOGIN",
    SCO.FST_NAME AS "NOME",
    SCO.LAST_NAME AS "SOBRENOME"
FROM SIEBEL.S_APPLET AP
INNER JOIN SIEBEL.S_USER SUS ON SUS.ROW_ID = AP.OBJ_LOCKED_BY
INNER JOIN SIEBEL.S_CONTACT SCO ON SCO.ROW_ID = SUS.PAR_ROW_ID
WHERE AP.NAME = 'Quote Item List Applet';

UPDATE SIEBEL.S_APPLET AP
SET OBJ_LOCKED_FLG = 'N'
WHERE ROW_ID = '8-G4MXSA7';