SELECT
    BC.ROW_ID,
    BC.NAME,
    BC.TABLE_NAME,
    BC.OBJ_LOCKED_FLG,
    BC.OBJ_LOCKED_BY,
    SUS.ROW_ID AS "ID_USUARIO",
    SUS.LOGIN AS "LOGIN",
    SCO.FST_NAME AS "NOME",
    SCO.LAST_NAME AS "SOBRENOME"
FROM SIEBEL.S_BUSCOMP BC
INNER JOIN SIEBEL.S_USER SUS ON SUS.ROW_ID = BC.OBJ_LOCKED_BY
INNER JOIN SIEBEL.S_CONTACT SCO ON SCO.ROW_ID = SUS.PAR_ROW_ID
WHERE BC.NAME = 'NV Opportunity Navigation Flow BC';

UPDATE SIEBEL.S_BUSCOMP BC
SET OBJ_LOCKED_FLG = 'N'
WHERE ROW_ID = '8-G4MXSA7';