SELECT
    BO.ROW_ID,
    BO.NAME,
    BO.OBJ_LOCKED_FLG,
    BO.OBJ_LOCKED_BY,
    SUS.ROW_ID AS "ID_USUARIO",
    SUS.LOGIN AS "LOGIN",
    SCO.FST_NAME AS "NOME",
    SCO.LAST_NAME AS "SOBRENOME"
FROM SIEBEL.S_BUSOBJ BO
INNER JOIN SIEBEL.S_USER SUS ON SUS.ROW_ID = BO.OBJ_LOCKED_BY
INNER JOIN SIEBEL.S_CONTACT SCO ON SCO.ROW_ID = SUS.PAR_ROW_ID
WHERE BO.NAME = 'Account';

UPDATE SIEBEL.S_BUSOBJ BO
SET OBJ_LOCKED_FLG = 'N'
WHERE ROW_ID = '8-G4MXSA7';