SELECT
    PROD.ROW_ID,
    PROD.NAME,
    VOD.ROW_ID AS "ID_VOD",
    VOD.LOCKED_FLG,
	VOD.LOCKED_BY
FROM SIEBEL.S_PROD_INT PROD
INNER JOIN SIEBEL.S_VOD VOD ON VOD.OBJECT_NUM = PROD.CFG_MODEL_ID
WHERE NAME IN ('Fixo e Móvel Ilimitado Local Empresas Oferta - FSP');

UPDATE SIEBEL.S_VOD VOD
SET VOD.LOCKED_FLG = 'N',
	VOD.LOCKED_BY = NULL
WHERE VOD.ROW_ID IN ('8-8S90VKF');