SELECT
    PROJ.ROW_ID,
    PROJ.NAME AS "PROJETO",
    PROJ.LOCKED_FLG AS "BLOQUEADO",
    SUS.ROW_ID AS "ID_USUARIO",
    SUS.LOGIN AS "LOGIN",
    SCO.FST_NAME AS "NOME",
    SCO.LAST_NAME AS "SOBRENOME"
FROM SIEBEL.S_PROJECT PROJ
INNER JOIN SIEBEL.S_USER SUS ON SUS.ROW_ID = PROJ.LOCKED_BY
INNER JOIN SIEBEL.S_CONTACT SCO ON SCO.ROW_ID = SUS.PAR_ROW_ID
--WHERE PROJ.NAME = 'GVT External Systems';
WHERE SUS.LOGIN LIKE 'HSANTOS';

UPDATE SIEBEL.S_PROJECT PROJ
SET PROJ.LOCKED_FLG = 'N'
WHERE PROJ.ROW_ID = '1-KVYG-QBQ';
--IN ('8-I5GE-BUY','8-I5GE-BUH');