SELECT
    SC.ROW_ID,
    SC.NAME,
    SC.OBJ_LOCKED_FLG,
    SC.OBJ_LOCKED_BY,
    SUS.ROW_ID AS "ID_USUARIO",
    SUS.LOGIN AS "LOGIN",
    SCO.FST_NAME AS "NOME",
    SCO.LAST_NAME AS "SOBRENOME"
FROM SIEBEL.S_SCREEN SC
INNER JOIN SIEBEL.S_USER SUS ON SUS.ROW_ID = SC.OBJ_LOCKED_BY
INNER JOIN SIEBEL.S_CONTACT SCO ON SCO.ROW_ID = SUS.PAR_ROW_ID
WHERE SC.NAME = 'Accounts Screen';

UPDATE SIEBEL.S_SCREEN SC
SET OBJ_LOCKED_FLG = 'N'
WHERE ROW_ID = '2-T5G9-1I7QO';