SELECT
    WF.ROW_ID,
    WF.PROC_NAME,
    WF.VERSION,
    WF.OBJ_LOCKED_FLG,
	WF.OBJ_LOCKED_DATE
FROM SIEBEL.S_WFR_PROC WF
WHERE WF.PROC_NAME = 'GVT Order Creation WF'
ORDER BY WF.VERSION DESC;

update SIEBEL.S_WFR_PROC W
set W.OBJ_LOCKED_FLG = 'N',
	W.OBJ_LOCKED_DATE = null
where
    W.ROW_ID = '8-GUN0A61';